# Shell variables
# Generated by 'wal'
wallpaper='/home/marc/Pictures/Wallpapers/firewatch-forest-4k-1920×1080.jpg'

# Special
background='#282c34'
foreground='#e5c07b'
cursor='#b6bdca'

# Colors
color0='#282c34'
color1='#353b45'
color2='#3e4451'
color3='#545862'
color4='#565c64'
color5='#abb2bf'
color6='#b6bdca'
color7='#c8ccd4'
color8='#e06c75'
color9='#d19a66'
color10='#e5c07b'
color11='#98c379'
color12='#56b6c2'
color13='#61afef'
color14='#c678dd'
color15='#be5046'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
