# Shell variables
# Generated by 'wal'
wallpaper='/home/marc/Pictures/Wallpapers/firewatch-forest-4k-1920×1080.jpg'

# Special
background='#0d031b'
foreground='#f5e6ab'
cursor='#f5e6ab'

# Colors
color0='#0d031b'
color1='#B45943'
color2='#E3744D'
color3='#F18E3C'
color4='#F48E52'
color5='#EDA75B'
color6='#FAAC58'
color7='#f5e6ab'
color8='#aba177'
color9='#B45943'
color10='#E3744D'
color11='#F18E3C'
color12='#F48E52'
color13='#EDA75B'
color14='#FAAC58'
color15='#f5e6ab'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
