#!/usr/bin/env bash

function stripDir() {
	local strippedDir
	strippedDir=$(echo "$1" | rev | cut -d'/' -f-"$2" | rev)
	echo "$strippedDir"
}

if [[ -z $1 ]]; then
	DOTFILE_DIR="$HOME/Documents/config/dotfiles"
else
	DOTFILE_DIR=$1
fi

# nvim
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

for f in $(find "$DOTFILE_DIR"/nvim -maxdepth 1 -regex ".*\.vim$"); do
	strippedDir=$(stripDir "$f" 2)
	echo "Linking $f to ~/.config/$strippedDir"
	rm -rf ~/.config/"$strippedDir"
	ln -s "$f" ~/.config/"$strippedDir"
done

for f in $(find "$DOTFILE_DIR"/nvim/plugin -maxdepth 1 -regex ".*\.vim$"); do
	strippedDir=$(stripDir "$f" 3)
	echo "Linking $f to ~/.config/$strippedDir"
	rm -rf ~/.config/"$strippedDir"
	ln -s "$f" ~/.config/"$strippedDir"
done

# homedir
for f in $(find "$DOTFILE_DIR"/homedir -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/homedir/$f to ~/$f"
	rm -rf ~/"$f"
	ln -s "$DOTFILE_DIR"/homedir/"$f" ~/"$f"
done

# vscode
mkdir -p ~/Library/Application\ Support/Code/User
for f in $(find "$DOTFILE_DIR"/vscode -maxdepth 1 -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/vscode/$f to ~/Library/Application\ Support/Code/User/$f"
	rm -rf ~/Library/Application\ Support/Code/User/"$f"
	ln -s "$DOTFILE_DIR/vscode/$f" ~/Library/Application\ Support/Code/User/"$f"
done

mkdir -p ~/Library/Application\ Support/Code/User/snippets
for f in $(find "$DOTFILE_DIR"/vscode/snippets -maxdepth 1 -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/vscode/snippets/$f to ~/Library/Application\ Support/Code/User/snippets/$f"
	rm -rf ~/Library/Application\ Support/Code/User/snippets/"$f"
	ln -s "$DOTFILE_DIR/vscode/snippets/$f" ~/Library/Application\ Support/Code/User/snippets/"$f"
done
