#!/usr/bin/env bash

function stripDir() {
	local strippedDir
	strippedDir=$(echo "$1" | rev | cut -d'/' -f-"$2" | rev)
	echo "$strippedDir"
}

if [[ -z $1 ]]; then
	DOTFILE_DIR="$HOME/Documents/config/dotfiles"
else
	DOTFILE_DIR=$1
fi

#nvim with nvchad
mkdir -p ~/.config/nvim/lua/custom
mkdir -p ~/.config/nvim/lua/custom/configs

for f in $(find "$DOTFILE_DIR"/nvchad/custom -maxdepth 1 -regex ".*\.lua$"); do
	strippedDir=$(stripDir "$f" 1)
	echo "Linking $f to ~/.config/nvim/lua/custom/$strippedDir"
	rm -rf ~/.config/nvim/lua/custom/"$strippedDir"
	ln -s "$f" ~/.config/nvim/lua/custom/"$strippedDir"
done

for f in $(find "$DOTFILE_DIR"/nvchad/custom/configs -maxdepth 1 -regex ".*\.lua$"); do
	strippedDir=$(stripDir "$f" 1)
	echo "Linking $f to ~/.config/nvim/lua/custom/configs/$strippedDir"
	rm -rf ~/.config/nvim/lua/custom/configs/"$strippedDir"
	ln -s "$f" ~/.config/nvim/lua/custom/configs/"$strippedDir"
done

# homedir
for f in $(find "$DOTFILE_DIR"/homedir -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/homedir/$f to ~/$f"
	rm -rf ~/"$f"
	ln -s "$DOTFILE_DIR"/homedir/"$f" ~/"$f"
done
#
# config dir
for f in $(find "$DOTFILE_DIR"/configdir -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/configdir/$f to ~/.config/$f"
	rm -rf ~/.config/"$f"
	ln -s "$DOTFILE_DIR"/configdir/"$f" ~/.config/"$f"
done

# vscode
mkdir -p ~/Library/Application\ Support/Code/User
for f in $(find "$DOTFILE_DIR"/vscode -maxdepth 1 -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/vscode/$f to ~/Library/Application\ Support/Code/User/$f"
	rm -rf ~/Library/Application\ Support/Code/User/"$f"
	ln -s "$DOTFILE_DIR/vscode/$f" ~/Library/Application\ Support/Code/User/"$f"
done

mkdir -p ~/Library/Application\ Support/Code/User/snippets
for f in $(find "$DOTFILE_DIR"/vscode/snippets -maxdepth 1 -type f -exec basename {} \;); do
	echo "Linking $DOTFILE_DIR/vscode/snippets/$f to ~/Library/Application\ Support/Code/User/snippets/$f"
	rm -rf ~/Library/Application\ Support/Code/User/snippets/"$f"
	ln -s "$DOTFILE_DIR/vscode/snippets/$f" ~/Library/Application\ Support/Code/User/snippets/"$f"
done
