#!/usr/bin/env bash

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

for f in `find . -regex ".*\.vim$"`; do
	rm -rf ~/.config/nvim/$f
	ln -s ~/Documents/dotfiles/nvim/$f ~/.config/nvim/$f
done
