#!/bin/sh

# Sets up monitors
xrandr --output DP-0 --primary

xrandr --output DP-0 --right-of DP-4
xrandr --output DP-2 --right-of DP-0

xrandr --output DP-4 --mode 1920x1080 --rate 144
xrandr --output DP-0 --mode 2560x1440 --rate 144
xrandr --output DP-2 --mode 1920x1080 --rate 60
xrandr --output DP-2 --rotate left

xrandr --output DP-4 --pos 0x50

bspc monitor DP-0 -s DP-4
bspc monitor DP-0 -d 1 2 3 4
bspc monitor DP-4 -d 5 6 7
bspc monitor DP-2 -d 8 9 0

# Don't turn off monitors
xset s off -dpms

# Lowers mouse sensitivity
xinput --set-prop 'Logitech Gaming Mouse G502' 'libinput Accel Speed' -0.6
# Stops the X cursor when not hovering over a window
xsetroot -cursor_name left_ptr

feh --bg-center ~/Pictures/Wallpapers/system/wallpaper.jpg

$HOME/.config/polybar/launch.sh

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config click_to_focus true

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc rule -a Peek state=floating
bspc rule -a Soffice state=tiled

# Application startups
sxhkd &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
dropbox start &
discord &
