#!/bin/sh

sxhkd &
 
# Sets up monitors
xrandr --output DP-0 --primary
xrandr --output DVI-I-0 --rotate right
xrandr --output DP-0 --right-of DP-4
xrandr --output DVI-I-0 --right-of DP-0
xrandr --output DP-0 --mode 1920x1080 --rate 144.00
xrandr --output DP-4 --mode 1920x1080 --rate 74.92

# Lowers mouse sensitivity
xinput --set-prop 'Logitech Gaming Mouse G502' 'libinput Accel Speed' -0.6
# Stops the X cursor when not hovering over a window
xsetroot -cursor_name left_ptr

feh --bg-center ~/Pictures/Wallpapers/firewatch-forest-4k-3840×2160.jpg

$HOME/.config/polybar/launch.sh

# Three monitor setup
bspc monitor DP-0 -d 1 2 3 4
bspc monitor DP-4 -d 5 6
bspc monitor DVI-I-0 -d 7 8 9 10
bspc monitor DP-4 -s DP-0

# Dual monitor setup
#bspc monitor DP-0 -d 1 2 3 4 5
#bspc monitor DVI-I-0 -d 6 7 8 9 0

bspc config focused_border_color \#ffb52a
bspc config active_border_color \#555555
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Peek state=floating
